/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.UsuarioControl;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ANDRES
 */
public class vistaCrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form crearUsuario
     */
    public vistaCrearUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idUsuarioo = new javax.swing.JTextField();
        cedulaNueva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contrasenaNueva = new javax.swing.JPasswordField();
        Aceptar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        usuarioNuevo = new javax.swing.JTextField();
        nuevoAdministrador = new javax.swing.JCheckBox();
        nuevoReclutador = new javax.swing.JCheckBox();
        nuevoCapacitador = new javax.swing.JCheckBox();
        nuevoGestor = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ventana para crear usuario nuevo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 250, 30));
        getContentPane().add(idUsuarioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 150, 30));
        getContentPane().add(cedulaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula Trabajador :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, 20));
        getContentPane().add(contrasenaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, 30));

        Aceptar.setBackground(new java.awt.Color(0, 0, 153));
        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Crear");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccionar Roles ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administrador Sistema");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 160, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capacitador");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 130, 30));

        Atras.setBackground(new java.awt.Color(0, 0, 102));
        Atras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gestor de nomina");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reclutador");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre usuario :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, 30));
        getContentPane().add(usuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 150, 30));
        getContentPane().add(nuevoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 20, 20));
        getContentPane().add(nuevoReclutador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));
        getContentPane().add(nuevoCapacitador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));
        getContentPane().add(nuevoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed

        String nuevoUsuario = usuarioNuevo.getText();
        char[] arrayC = contrasenaNueva.getPassword(); 
        String pass = new String(arrayC); 
        String contrasenaNueva = pass;
        String nuevaCedula = cedulaNueva.getText();
        ArrayList rolesEscogidos = new ArrayList(4);
        
        int idUsuario = Integer.parseInt(idUsuarioo.getText());
        rolesEscogidos.add(false);
        rolesEscogidos.add(false);
        rolesEscogidos.add(false);
        rolesEscogidos.add(false);
        
        
        if(nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,true);
        }else if(nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,true);
        }else if(nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,false);
        }else if(nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,false);
        }else if(nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,true);
        }else if(!nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,true);
        }else if(!nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,true);
        }else{
            System.out.println("No se selecciono lo roles correctamente");
        }
        
        UsuarioControl controlCrearUsuario = new UsuarioControl(idUsuario,nuevoUsuario,contrasenaNueva,rolesEscogidos,nuevaCedula);
        
        try {
            if(controlCrearUsuario.guardarUsuario()){
                vistaUsuarioCreado usuarioExitoso = new vistaUsuarioCreado();
                usuarioExitoso.setVisible(true);
            }else{
                //error al guardar por algun motivo
            }
                               
                } catch (SQLException ex) {
            Logger.getLogger(vistaCrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaAdministradorSistema vistaanterior= new VistaAdministradorSistema();
        vistaanterior.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Atras;
    private javax.swing.JTextField cedulaNueva;
    private javax.swing.JPasswordField contrasenaNueva;
    private javax.swing.JTextField idUsuarioo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox nuevoAdministrador;
    private javax.swing.JCheckBox nuevoCapacitador;
    private javax.swing.JCheckBox nuevoGestor;
    private javax.swing.JCheckBox nuevoReclutador;
    private javax.swing.JTextField usuarioNuevo;
    // End of variables declaration//GEN-END:variables
}
