/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Control.UsuarioControl;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ANDRES
 */
public class vistaActualizarUsuario extends javax.swing.JFrame {

    /** Creates new form vistaActualizarUsuario */
    public vistaActualizarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usuarioACambiar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ConsultarCedula = new javax.swing.JTextField();
        nuevoIdUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nuevoUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nuevoAdministrador = new javax.swing.JCheckBox();
        nuevoGestor = new javax.swing.JCheckBox();
        nuevoReclutador = new javax.swing.JCheckBox();
        nuevoCapacitador = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        nuevaContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Contraseña : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capacitador :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 130, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Consultar Usuario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cedula del trabajador : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 180, 40));
        getContentPane().add(usuarioACambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nuevo Id Usuario : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 40));
        getContentPane().add(ConsultarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 130, -1));
        getContentPane().add(nuevoIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nuevo Usuario : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, 40));
        getContentPane().add(nuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ventana para actualizar usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 250, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Escoger Roles :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Administrador Sistema : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 200, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gestor Nomina :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 130, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reclutador :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 130, 40));
        getContentPane().add(nuevoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));
        getContentPane().add(nuevoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));
        getContentPane().add(nuevoReclutador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));
        getContentPane().add(nuevoCapacitador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));
        getContentPane().add(nuevaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        VistaAdministradorSistema vistaAnterior = new VistaAdministradorSistema();
        vistaAnterior.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList rolesEscogidos = new ArrayList(4);
        UsuarioControl controll = new UsuarioControl(0,"","",rolesEscogidos,ConsultarCedula.getText());
        try {
            String nombreEncontrado = controll.devolverUsuario().validarCedula();
            if(nombreEncontrado.equals("")){
                vistaUsuarioNoEncontrado error = new vistaUsuarioNoEncontrado();
                error.setVisible(true);
            }else{
                usuarioACambiar.setText(nombreEncontrado);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(vistaActualizarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        char[] arrayC = nuevaContrasena.getPassword(); 
        String pass = new String(arrayC); 
        String contrasenaNueva = pass;
        ArrayList rolesEscogidos = new ArrayList(4);
        int idUsuario = Integer.parseInt(nuevoIdUsuario.getText());
        rolesEscogidos.add(false);
        rolesEscogidos.add(false);
        rolesEscogidos.add(false);
        rolesEscogidos.add(false);
        
        
        if(nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,true);
        }else if(nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,true);
        }else if(nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,false);
        }else if(nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,false);
        }else if(nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,true);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,true);
        }else if(!nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && !nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,false);
        }else if(!nuevoAdministrador.isSelected() && nuevoGestor.isSelected() && !nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,true);
            rolesEscogidos.set(2,false);
            rolesEscogidos.set(3,true);
        }else if(!nuevoAdministrador.isSelected() && !nuevoGestor.isSelected() && nuevoCapacitador.isSelected() && nuevoReclutador.isSelected()){
            rolesEscogidos.set(0,false);
            rolesEscogidos.set(1,false);
            rolesEscogidos.set(2,true);
            rolesEscogidos.set(3,true);
        }else{
            System.out.println("No se selecciono lo roles correctamente");
        }                  
        
        UsuarioControl controll = new UsuarioControl(idUsuario,nuevoUsuario.getText(),contrasenaNueva,rolesEscogidos,ConsultarCedula.getText());
        try {
            if(controll.devolverUsuario().actualizar()){
                VistaUsuarioActualizado exito = new VistaUsuarioActualizado();
                exito.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(vistaActualizarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConsultarCedula;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField nuevaContrasena;
    private javax.swing.JCheckBox nuevoAdministrador;
    private javax.swing.JCheckBox nuevoCapacitador;
    private javax.swing.JCheckBox nuevoGestor;
    private javax.swing.JTextField nuevoIdUsuario;
    private javax.swing.JCheckBox nuevoReclutador;
    private javax.swing.JTextField nuevoUsuario;
    private javax.swing.JTextField usuarioACambiar;
    // End of variables declaration//GEN-END:variables

}
